language: javascript
node_js: 9
cache:
  directories:
    - $HOME/.npm
env:
  global:
    - PATH=$PATH:/packer/packer
before_install:
  - wget https://releases.hashicorp.com/packer/$PACKER_VERSION/packer_1.2.2_linux_amd64.zip && unzip packer_*.zip -d packer
install:
  - npm --prefix tools/automake install
script: node tools/automake/index.js
