language: node_js
node_js:
  - "9"
cache:
  directories:
    - packer
    - $HOME/.npm
addons:
  apt:
    - zip
    - virtualbox
before_install:
  - |
    if [ -d "packer" ]; then
      wget https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_linux_amd64.zip
      unzip packer_*.zip -d packer
    fi
    export PATH="$PATH:/packer/packer"
  - |
    pushd tools/automake
    npm install
    popd
script: node tools/automake/index.js
