language: javascript
node_js: 9
cache:
  directories:
    - $HOME/.npm
before_install:
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ruby-full linux-headers-generic linux-headers-virtual apt-transport-https libssl-dev libffi-dev ca-certificates zip unzip build-essential software-properties-common curl wget
  - |
    echo "Setuping custom repos"
    # VAR SETUP
    export LINUX_DISTR="$(lsb_release -c -s)"
    export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
    echo "$LINUX_DISTR"
    echo "$CLOUD_SDK_REPO"
    # GOOGLE CLOUD
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    curl -L https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    # VIRTUALBOX
    echo "deb https://download.virtualbox.org/virtualbox/debian $LINUX_DISTR contrib" | sudo tee -a /etc/apt/sources.list.d/virtualbox.list
    curl -L https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo apt-key add -
    curl -L https://www.virtualbox.org/download/oracle_vbox.asc | sudo apt-key add -
    # DOCKER
    echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $LINUX_DISTR stable" | sudo tee -a /etc/apt/sources.list.d/docker.list
    curl -L https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo apt-key fingerprint 0EBFCD88
    # AZURE
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $LINUX_DISTR main" | sudo tee -a /etc/apt/sources.list.d/azure.list
    curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893
    # UPDATE APT
    sudo apt-get update
  - |
    sudo DEBIAN_FRONTEND=noninteractive apt-get -y -q install virtualbox
    LatestVirtualBoxVersion=$(wget -qO - http://download.virtualbox.org/virtualbox/LATEST.TXT)
    wget "http://download.virtualbox.org/virtualbox/${LatestVirtualBoxVersion}/Oracle_VM_VirtualBox_Extension_Pack-${LatestVirtualBoxVersion}.vbox-extpack"
    sudo VBoxManage extpack install --replace Oracle_VM_VirtualBox_Extension_Pack-${LatestVirtualBoxVersion}.vbox-extpack
    sudo VBoxManage list extpacks
    rm -rf Oracle_VM_VirtualBox_Extension_Pack-${LatestVirtualBoxVersion}.vbox-extpack
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -q install qemu qemu-kvm virt-manager virt-viewer libvirt-bin
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -q install azure-cli dirmngr psmisc
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -q install python-vm-builder-ec2
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -q install open-vm-tools
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -q install docker-ce
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -q install google-cloud-sdk
  - sudo npm install -g yarn
  - |
    wget https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_linux_amd64.zip
    unzip packer_*.zip -d packer
    rm -rf packer_*.zip
    mv packer /usr/local
    echo 'export PATH="$PATH:/usr/local/packer"' >> /etc/environment
    export PATH="$PATH:/usr/local/packer"
    packer
jobs:
  include:
    - stage: regenerate templates
      scripts:
        - cd tools/automake/
        - npm install
        - node index.js
        - cd ../..
