language: javascript
image: impresscms/packer-builder
cache:
  directories:
    - $HOME/.npm
jobs:
  include:
    - stage: regenerate templates
      scripts:
        - cd tools/automake/
        - npm install
        - node index.js
        - cd ../..
