before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y -q zip
  - wget https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_linux_amd64.zip
  - unzip packer_*.zip -d packer
  - export PATH="$PATH:/packer/packer"
  - packer
