language: javascript
node_js: 9
cache:
  directories:
    - $HOME/.npm
env:
  global:
    - PACKER_VERSION=1.2.2
    - PATH=$PATH:/packer/packer
before_install:
  - wget https://releases.hashicorp.com/packer/$PACKER_VERSION/packer_$PACKER_VERSION_linux_amd64.zip && unzip packer_$PACKER_VERSION_linux_amd64.zip -d packer
  - npm --prefix tools/automake install
script: node tools/automake/index.js
