sudo: required
dist: trusty
language: node_js
nvm: 9.11.1
node_js: 9
cache:
  yarn: true
  directories:
    - $HOME/.npm
services:
  - docker
addons:
  apt:
    sources:
      - google-cloud
      - heroku
    packages:
      - linux-headers-generic
      - linux-headers-virtual
      - apt-transport-https
      - libssl-dev
      - libffi-dev
      - ca-certificates
      - zip
      - unzip
      - build-essential
      - software-properties-common
      - curl
      - wget
      - qemu
      - qemu-kvm
      - virt-manager
      - virt-viewer
      - libvirt-bin
      - open-vm-tools
      - google-cloud-sdk
      - python-vm-builder-ec2
before_install:
  - |
    echo "Setuping custom repos"
    # VAR SETUP
    export LINUX_DISTR="$(lsb_release -c -s)"
    echo "$LINUX_DISTR"
    echo "$CLOUD_SDK_REPO"
    # VIRTUALBOX
    echo "deb https://download.virtualbox.org/virtualbox/debian $LINUX_DISTR contrib" | sudo tee -a /etc/apt/sources.list.d/virtualbox.list
    curl -L https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo apt-key add -
    curl -L https://www.virtualbox.org/download/oracle_vbox.asc | sudo apt-key add -
    # AZURE
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $LINUX_DISTR main" | sudo tee -a /etc/apt/sources.list.d/azure.list
    curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893
    # UPDATE APT
    sudo apt-get update
  - |
    sudo DEBIAN_FRONTEND=noninteractive apt-get -y -q install virtualbox
    LatestVirtualBoxVersion=$(wget -qO - http://download.virtualbox.org/virtualbox/LATEST.TXT)
    wget "http://download.virtualbox.org/virtualbox/${LatestVirtualBoxVersion}/Oracle_VM_VirtualBox_Extension_Pack-${LatestVirtualBoxVersion}.vbox-extpack"
    sudo VBoxManage extpack install --replace Oracle_VM_VirtualBox_Extension_Pack-${LatestVirtualBoxVersion}.vbox-extpack
    sudo VBoxManage list extpacks
    rm -rf Oracle_VM_VirtualBox_Extension_Pack-${LatestVirtualBoxVersion}.vbox-extpack
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -q install azure-cli dirmngr psmisc
  - |
    wget https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_linux_amd64.zip
    unzip packer_*.zip -d packer
    rm -rf packer_*.zip
    mv packer /usr/local
    echo 'export PATH="$PATH:/usr/local/packer"' >> /etc/environment
    export PATH="$PATH:/usr/local/packer"
    packer
jobs:
  include:
    - stage: regenerate templates
      script: |
        pushd tools/automake/
        npm install
        node index.js
        popd
