language: javascript
node_js: 9
sudo: true
cache:
  directories:
    - $HOME/.npm
before_install:
  - DEBIAN_FRONTEND=noninteractive apt-get -y install ruby-full node npm linux-headers-generic linux-headers-virtual apt-transport-https libssl-dev libffi-dev ca-certificates zip unzip build-essential software-properties-common curl wget
  - |
    echo "Setuping custom repos"
    # VAR SETUP
    export LINUX_DISTR="$(lsb_release -c -s)"
    # GOOGLE CLOUD
    export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    curl -L https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    # VIRTUALBOX
    echo "deb https://download.virtualbox.org/virtualbox/debian $LINUX_DISTR contrib" | tee -a /etc/apt/sources.list.d/virtualbox.list
    curl -L https://www.virtualbox.org/download/oracle_vbox_2016.asc | apt-key add -
    curl -L https://www.virtualbox.org/download/oracle_vbox.asc | apt-key add -
    # DOCKER
    echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $LINUX_DISTR stable" | tee -a /etc/apt/sources.list.d/docker.list
    curl -L https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    apt-key fingerprint 0EBFCD88
    # AZURE
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $LINUX_DISTR main" | tee -a /etc/apt/sources.list.d/azure.list
    curl -L https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
    apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893
    # UPDATE APT
    apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get -y install virtualbox virtualbox-ext-pack
  - DEBIAN_FRONTEND=noninteractive apt-get -y install qemu qemu-kvm virt-manager virt-viewer libvirt-bin
  - DEBIAN_FRONTEND=noninteractive apt-get -y install azure-cli dirmngr psmisc
  - DEBIAN_FRONTEND=noninteractive apt-get -y install python-vm-builder-ec2
  - DEBIAN_FRONTEND=noninteractive apt-get -y install open-vm-tools
  - DEBIAN_FRONTEND=noninteractive apt-get -y install docker-ce
  - DEBIAN_FRONTEND=noninteractive apt-get -y install google-cloud-sdk
  - npm install -g yarn
jobs:
  include:
    - stage: regenerate templates
      scripts:
        - cd tools/automake/
        - npm install
        - node index.js
        - cd ../..
