language: javascript
image: impresscms/packer-builder
cache:
  directories:
    - $HOME/.npm
jobs:
  include:
    - stage: Install requirements
      script: npm --prefix tools/automake install
    - stage: Regenerate templates
      script: node tools/automake/index.js
